# https://doc.rust-lang.org/cargo/reference/config.html
[build]
target-dir = "/tmp"

# Optimizing for native CPU platform
# https://wiki.archlinux.org/title/Rust#Optimizing_for_native_CPU_platform
[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = [
  #"-Awarnings",
  "-Aunused_parens",
  "-Adead_code",
  "-C", "target-cpu=native",
  "-C", "link-arg=-fuse-ld=lld",
  # Profile guided optimization:
  # https://doc.rust-lang.org/rustc/profile-guided-optimization.html
  #"-C", "profile-generate=/tmp/pgo",
  #llvm-profdata merge -o /tmp/pgo/merged.profdata /tmp/pgo
  #"-C", "profile-use=/tmp/pgo/merged.profdata",
]

[profile.release]
debug = "limited"

# USAGE: cargo build --profile optimized
[profile.optimized]
inherits = "release"
lto = true
codegen-units = 1
#debug = "none"
panic = "abort"

