" Use Vim settings, rather than Vi settings (much better!).
" This must be first, because it changes other options as a side effect.
set nocompatible
colorscheme darkblue

set ignorecase
set complete=.,w,b,u,t

" Indent options and tab width
set autoindent
set tabstop=2
set expandtab
set shiftwidth=2

" Display options: line number, statusline, current command
set number
set laststatus=2
set statusline=%t%h%m%r%y%=%c,\ %l/%L\ \ %P
set showcmd

" Buffer options
set hidden

""""""""""""""
" Mappings """
""""""""""""""
nnoremap <Space> <C-D>
nnoremap <F1> wbyw
nnoremap <F2> wb"_dwP
nnoremap Y y$
nnoremap gb :bn<CR>

" Do not copy text each time something is deleted
nnoremap cw "_cw
nnoremap dw "_dw
nnoremap D "_D
nnoremap C "_C
nnoremap cc "_cc
nnoremap x "_x
nnoremap r "_r

nnoremap u <C-u>
nnoremap U u
nnoremap <CR> o<Esc>
nnoremap <Backspace> i<Backspace><Esc>l

" The q letter just brings troubles
nnoremap Q q
nnoremap q <Esc>

" Normal paste respects indentation
nnoremap p ]p
nnoremap P [P

inoremap <C-a> <Home>
inoremap <C-e> <End>

" C-@ is a workaround to have autocompletion using same shortcut as eclipse
inoremap <C-Space> <C-n>
inoremap <C-@> <C-n>
nnoremap <C-Space> cw<C-n>
nnoremap <C-@> cw<C-n>

cnoremap sss %s///gi<Home><right><right><right>
cnoremap lll .s///gi<Home><right><right><right>
cnoremap rrr .,.+s///gi<Home><right><right><right><right>

" Switch syntax highlighting on, when the terminal has colors
" Also switch on highlighting the last used search pattern.
if &t_Co > 2 || has("gui_running")
  syntax enable
  set hlsearch
endif

" Disable f**king ftp plugins that overwrite my vimrc (http://peox.net/articles/vimconfig.html)
filetype plugin indent off

" Disable plugins selectively (http://vi.stackexchange.com/questions/4257/how-do-i-prevent-vim-from-loading-plugins-on-older-configurations)
"let g:loaded_netrwPlugin = "no_thanks"

